cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ghost:
      email: test@gmail.com
      name: ghost
      password: $2b$12$4hEntUrG3GZdDexg5OFihO9pO8anFiclh4583NygtrRY66BGxNjK.
    john:
      email: ghost
      name: john
      password: $2b$12$mks0E3SU.gfUCWf.klAmAuC6LjyD5u4iHGJFeiDLbYkWKmykxD576
    jsmith:
      email: test@gmail.com
      name: P
      password: '123'
    p:
      email: test@gmail.com
      name: Paula
      password: $2b$12$3lNMo.RbEUZAlFOXJh3fRuwd0ei9N8UhFVSGZ2x2.XEtgS0KBgvwO
    rbriggs:
      email: test@gmail.com
      name: P
      password: '456'
preauthorized:
  emails:
  - test@gmail.com
